import assert from 'node:assert/strict';
import worker,{validate} from '../functions/contact-worker.mjs';
const valid={name:'آزمایش',contact:'test@example.com',service:'01',message:'یک سایت برای معرفی خدمات و نمایش پروژه‌ها می‌خواهم.',website:''};
assert(validate(valid));assert.equal(validate({...valid,name:'a'}),null);assert.equal(validate({...valid,message:'short'}),null);assert.equal(validate({...valid,service:'99'}),null);assert.equal(validate({...valid,website:'bot'}),null);assert.equal(validate({...valid,contact:'broken@'}),null);assert(validate({...valid,contact:'۰۹۱۲۱۲۳۴۵۶۷'}));assert.equal(validate({...valid,message:'x'.repeat(4001)}),null);assert.equal(validate({...valid,name:{}}),null);
const env={ALLOWED_ORIGIN:'https://portfolio.example',RATE_LIMITER:{limit:async()=>({success:true})},RESEND_API_KEY:'test-only',CONTACT_RECIPIENT:'test@example.com',CONTACT_FROM:'Portfolio <test@example.com>'};
const req=(body,origin=env.ALLOWED_ORIGIN)=>new Request('https://contact.example/',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(body)});
assert.equal((await worker.fetch(req(valid,'https://untrusted.example'),env)).status,403);assert.equal((await worker.fetch(req(valid),{...env,RATE_LIMITER:{limit:async()=>({success:false})}})).status,429);assert.equal((await worker.fetch(req({...valid,message:'a'}),env)).status,422);assert.equal((await worker.fetch(req(valid),{...env,RESEND_API_KEY:''})).status,503);assert.equal((await worker.fetch(req({...valid,message:'x'.repeat(17000)}),env)).status,413);
const saved=globalThis.fetch;try{globalThis.fetch=async()=>new Response('{"error":"failed"}',{status:502});assert.equal((await worker.fetch(req(valid),env)).status,502);globalThis.fetch=async()=>new Response('{"id":"test_delivery"}',{status:200});const response=await worker.fetch(req(valid),env);assert.equal(response.status,200);assert.deepEqual(await response.json(),{success:true});}finally{globalThis.fetch=saved;}
console.log('16 contact-worker validation and delivery checks passed (mocked delivery).');
